# Generated by Django 5.2.10 on 2026-01-19 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('summary', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('link', models.URLField(blank=True)),
                ('created_at', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at', 'title'],
            },
        ),
    ]
